### Create a user
POST http://localhost:3000/auth/signup
content-type: application/json 

{
  "email": "holla@gmail.com",
  "password": "testttt"
}

### login a user
POST http://localhost:3000/auth/signin
content-type: application/json 

{
  "email": "holla@gmail.com",
  "password": "testttt"
}

### Find a user with ID 
GET http://localhost:3000/auth/5

### Find all users with a given email
GET http://localhost:3000/auth?email=hellos@gmail.com

### Remove a user with ID 
DELETE  http://localhost:3000/auth/1

### update only email
PATCH http://localhost:3000/auth/2
content-type: application/json 

{
  "email": "BBBBBBadsds@gmail.com"
}

### update only password
PATCH http://localhost:3000/auth/2
content-type: application/json 

{
  "password": "BBBBBBadsds@gmail.com"
}

### Set a color to try cookie session
GET http://localhost:3000/auth/colors/red

### Set a color to try cookie session
GET http://localhost:3000/auth/colors

### Get currently signedUser
GET http://localhost:3000/auth/whoAmI

### Signeout
POST http://localhost:3000/auth/signout